# generated by datamodel-codegen:
#   filename:  course_schema_v2024-01-05.json
#   timestamp: 2024-01-05T13:29:13+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Location(BaseModel):
    value: Optional[str] = Field(None, title='Value')


class Date(BaseModel):
    value: Optional[str] = Field(None, title='Value')


class LanguageRequirement(BaseModel):
    language: Optional[str] = Field(None, title='Language')
    test: Optional[str] = Field(None, title='Test')
    score: Optional[str] = Field(None, title='Score')


class Module(BaseModel):
    type: Optional[str] = Field(None, title='Type')
    title: Optional[str] = Field(None, title='Title')
    link: Optional[str] = Field(None, title='Link')


class Tuition(BaseModel):
    study_mode: Optional[str] = Field(None, title='Study Mode')
    duration: Optional[str] = Field(None, title='Duration')
    student_category: Optional[str] = Field(None, title='Student Category')
    fee: Optional[str] = Field(None, title='Fee')


class Course(BaseModel):
    schema_version: str = Field(..., title='Schema Version')
    academic_year: str = Field(..., title='Academic Year')
    link: Optional[str] = Field(None, title='Link')
    title: str = Field(..., title='Title')
    study_level: Optional[str] = Field(None, title='Study Level')
    qualification: Optional[str] = Field(None, title='Qualification')
    university_title: str = Field(..., title='University Title')
    locations: List[Location] = Field(..., title='Locations')
    description: Optional[str] = Field(None, title='Description')
    about: Optional[str] = Field(None, title='About')
    start_dates: List[Date] = Field(..., title='Start Dates')
    application_dates: List[Date] = Field(..., title='Application Dates')
    entry_requirements: Optional[str] = Field(None, title='Entry Requirements')
    language_requirements: List[LanguageRequirement] = Field(
        ..., title='Language Requirements'
    )
    modules: List[Module] = Field(..., title='Modules')
    tuitions: List[Tuition] = Field(..., title='Tuitions')
